# Default values for cahoots-in.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

cahoots_url: "https://keycloak.fulltest.co/"
# namespace: in-cahoots

image:
  repository: gabrielfalcao/k8s-cahoots-in
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 5000

kibana:
  enabled: false
  service:
    type: NodePort
    port: 5601

authlib:
  google_client_id: 1038792448154-021rkeud407r8dsj6ftiuipgbn22hajc.apps.googleusercontent.com
  google_client_secret: 7mxH6VHvIka56pLuCxsHMYsS

ngrok:
  enabled: false
  bindtls: both
  image:
    repository: wernight/ngrok
    tag: latest
    pullPolicy: Always

  token: "34DAA242kqHzC3z1PxsnG_4hehzoCdvw7qbi5768QQg"
  subdomain: pron-f1l3-serv3r  # from "https:///pron-f1l3-serv3r.ngrok.io/"

zmq:
  enabled: false
  type: NodePort
  router_port: 4242
  dealer_port: 6969
  publisher_port: 5353
  subscriber_port: 5858

elasticsearch:
  enabled: false
  fullnameOverride: infrastructure-elasticsearch

ingress:
  enabled: true

oauth2:
  enabled: true
  domain: "id.t.newstore.net"
  callback_url: "https://keycloak.fulltest.co/callback/oauth2"

  # https://manage.auth0.com/dashboard/us/dev-newstore/applications/N6l4Wi2JmIh5gXiGj2sibsZiJRJu0jj1/settings
  client_id: "---injected by Makefile---"
  client_secret: "---injected by Makefile---"
  base_url: "https://id.t.newstore.net/realms/gabriel-NA-43928/protocol/openid-connect/"
  access_token_url: "https://id.t.newstore.net/realms/gabriel-NA-43928/protocol/openid-connect/token"
  authorize_url: "https://id.t.newstore.net/realms/gabriel-NA-43928/protocol/openid-connect/auth"
  client_scope: "openid profile email roles role_list profile picture email_verified"
  audience: "https://keycloak.fulltest.co"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
postgresql:
  fullnameOverride: cahoots-db
  enabled: true
  image:
    repository: postgres
    tag: 10.6

  postgresqlDataDir: /cahoots.in/data/postgresql-10.6/pgdata
  persistence:
    enabled: true
    mountPath: /cahoots.in/data/postgresql-10.6
    existingClaim: pvc-cahoots-in
    size: 10Gi

  postgresqlPassword: b5fi41dz1BE4C22F44u
  postgresqlDatabase: cahoots_in
  postgresqlUsername: web
  # master:
  #   extraInitContainers:
  #   - image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
  #     imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
  #     name: create postgres users
  #     command: ['bash', '-c', '"echo \"grant all privileges on database cahoots_in to postgres\""']


redis:
  fullnameOverride: cahoots-redis
  enabled: false
  image:
    pullPolicy: IfNotPresent
  cluster:
    enabled: false
    slaveCount: 1
  master:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    persistence:
      enabled: true
      storageClass: do-retained-block-storage
  slave:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    persistence:
      enabled: true
      storageClass: do-retained-block-storage
  sentinel:
    enabled: false
  rbac:
    create: true
  usePassword: false
  metrics:
    enabled: false
    podAnnotations:
      sidecar.istio.io/inject: "false"
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
