# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: {{ include "cahoots-in.fullname" . }}-kibana
# spec:
#   minReadySeconds: 5
#   replicas: 1
#   revisionHistoryLimit: 10
#   selector:
#     matchLabels:
#       app.kubernetes.io/name: {{ include "cahoots-in.name" . }}-kibana
#       app.kubernetes.io/instance: {{ .Release.Name }}
#   template:
#     metadata:
#       labels:
#         app.kubernetes.io/name: {{ include "cahoots-in.name" . }}-kibana
#         app.kubernetes.io/instance: {{ .Release.Name }}

#     spec:
#       containers:
#       - image: "docker.elastic.co/kibana/kibana:7.5.1"
#         imagePullPolicy: {{ .Values.image.pullPolicy }}
#         name: {{ .Chart.Name }}
#         env:
#         - name: ELASTICSEARCH_HOSTS
#           value: http://{{ template "elasticsearch.hostname" . }}

#         ports:
#         - containerPort: {{ .Values.kibana.service.port }}
#           protocol: TCP
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ include "cahoots-in.fullname" . }}-kibana
#   labels:
#     app.kubernetes.io/name: {{ include "cahoots-in.name" . }}-kibana
#     app.kubernetes.io/instance: {{ .Release.Name }}

# spec:
#   type: {{ .Values.service.type }}
#   ports:
#     - port: {{ .Values.kibana.service.port }}
#       protocol: TCP
#       name: kibana
#   selector:
#     app.kubernetes.io/name: {{ include "cahoots-in.name" . }}-kibana
#     app.kubernetes.io/instance: {{ .Release.Name }}
