{{- if .Values.ngrok.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cahoots-in.fullname" . }}-ngrok-tunnel
spec:
  minReadySeconds: 5
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cahoots-in.name" . }}-ngrok-tunnel
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cahoots-in.name" . }}-ngrok-tunnel
        app.kubernetes.io/instance: {{ .Release.Name }}

    spec:
      containers:
      - image: "{{ .Values.ngrok.image.repository }}:{{ .Values.ngrok.image.tag }}"
        imagePullPolicy: {{ .Values.ngrok.image.pullPolicy }}
        name: {{ .Chart.Name }}
        # command:
        #   - http
        #   - '--authtoken'
        #   - '{{ .Values.ngrok.token | quote }}'
        #   - '--subdomain'
        #   - '{{ .Values.ngrok.subdomain | quote }}'
        #   - '--bindtls=true'
        #   - '--log=stderr'
        #   - '{{ include "cahoots-in.web.fqdn" . | quote }}'
        env:
          - name: NGROK_AUTH
            valueFrom:
              secretKeyRef:
                name: {{ include "cahoots-in.fullname" . }}-secrets
                key: ngrok-token

          - name: NGROK_SUBDOMAIN
            value: {{ .Values.ngrok.subdomain | quote }}

          - name: NGROK_DEBUG
            value: "true"

          - name: NGROK_BINDTLS
            value: {{ .Values.ngrok.bindtls | quote }}

          - name: NGROK_HOSTNAME
            value: "{{ .Values.ngrok.subdomain }}.ngrok.io"

          # due to a problem with the ngrok image the hostname:port
          # needs be provided here
          - name: NGROK_PORT
            value: {{ include "cahoots-in.web.fqdn" . | quote }}
{{- end }}
