name: ðŸ‘¾ React App Docker Image

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build React App for K8S
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: gabrielfalcao/nst-fakenom
        tag_with_ref: true  # prevent pushing "latest" tag
        tag_with_sha: true
        dockerfile: frontend/Dockerfile
        path: frontend/
        tags: "${{ github.sha }}"
